// @flow

const { MsgDecoder } = require("../msg/MsgDecoder")
const PKG_CatchFish_Item = require("./PKG/CatchFish/Item");
const PKG_CatchFish_MoveItem = require("./PKG/CatchFish/MoveItem");
const PKG_CatchFish_Events_Event = require("./PKG/CatchFish/Events/Event");
const PKG_CatchFish_Fish = require("./PKG/CatchFish/Fish");
const PKG_CatchFish_Configs_Item = require("./PKG/CatchFish/Configs/Item");
const PKG_CatchFish_Stages_StageElement = require("./PKG/CatchFish/Stages/StageElement");
const PKG_CatchFish_Weapon = require("./PKG/CatchFish/Weapon");
const PKG_CatchFish_ColorFish = require("./PKG/CatchFish/ColorFish");
const PKG_CatchFish_Configs_Fish = require("./PKG/CatchFish/Configs/Fish");
const PKG_CatchFish_Bullet = require("./PKG/CatchFish/Bullet");
const PKG_CatchFish_Configs_Cannon = require("./PKG/CatchFish/Configs/Cannon");
const PKG_CatchFish_Cannon = require("./PKG/CatchFish/Cannon");
const PKG_CatchFish_Stages_Emitter_RandomFishs = require("./PKG/CatchFish/Stages/Emitter_RandomFishs");
const PKG_CatchFish_Stages_Monitor_KeepBigFish = require("./PKG/CatchFish/Stages/Monitor_KeepBigFish");
const PKG_CatchFish_Events_NoMoney = require("./PKG/CatchFish/Events/NoMoney");
const PKG_CatchFish_Events_Refund = require("./PKG/CatchFish/Events/Refund");
const PKG_CatchFish_Events_FishDead = require("./PKG/CatchFish/Events/FishDead");
const PKG_CatchFish_Events_PushWeapon = require("./PKG/CatchFish/Events/PushWeapon");
const PKG_CatchFish_Events_Fire = require("./PKG/CatchFish/Events/Fire");
const PKG_CatchFish_Events_CloseAutoFire = require("./PKG/CatchFish/Events/CloseAutoFire");
const PKG_CatchFish_Events_CannonSwitch = require("./PKG/CatchFish/Events/CannonSwitch");
const PKG_CatchFish_Events_CloseAutoLock = require("./PKG/CatchFish/Events/CloseAutoLock");
const PKG_CatchFish_Events_Aim = require("./PKG/CatchFish/Events/Aim");
const PKG_CatchFish_Events_OpenAutoLock = require("./PKG/CatchFish/Events/OpenAutoLock");
const PKG_CatchFish_Events_PushFish = require("./PKG/CatchFish/Events/PushFish");
const PKG_CatchFish_Events_OpenAutoFire = require("./PKG/CatchFish/Events/OpenAutoFire");
const PKG_Generic_Success = require("./PKG/Generic/Success");
const PKG_CatchFish_Events_DebugInfo = require("./PKG/CatchFish/Events/DebugInfo");
const PKG_CatchFish_Stages_Stage = require("./PKG/CatchFish/Stages/Stage");
const PKG_CatchFish_Stages_Monitor_KeepFatFish = require("./PKG/CatchFish/Stages/Monitor_KeepFatFish");
const PKG_CatchFish_Stages_Monitor_KeepBombFish = require("./PKG/CatchFish/Stages/Monitor_KeepBombFish");
const PKG_CatchFish_Stages_Emitter_RingFishs = require("./PKG/CatchFish/Stages/Emitter_RingFishs");
const PKG_CatchFish_Stages_Emitter_CircleFishs = require("./PKG/CatchFish/Stages/Emitter_CircleFishs");
const PKG_CatchFish_Configs_Config = require("./PKG/CatchFish/Configs/Config");
const PKG_CatchFish_Configs_SpriteFrame = require("./PKG/CatchFish/Configs/SpriteFrame");
const PKG_CatchFish_Configs_Physics = require("./PKG/CatchFish/Configs/Physics");
const PKG_CatchFish_Configs_FishSpriteFrame = require("./PKG/CatchFish/Configs/FishSpriteFrame");
const PKG_CatchFish_Configs_BigFish = require("./PKG/CatchFish/Configs/BigFish");
const PKG_CatchFish_Configs_ColorFish = require("./PKG/CatchFish/Configs/ColorFish");
const PKG_CatchFish_Configs_Weapon = require("./PKG/CatchFish/Configs/Weapon");
const PKG_CatchFish_Events_CannonCoinChange = require("./PKG/CatchFish/Events/CannonCoinChange");
const PKG_CatchFish_Events_Leave = require("./PKG/CatchFish/Events/Leave");
const PKG_CatchFish_FuryBullet = require("./PKG/CatchFish/FuryBullet");
const PKG_CatchFish_DrillBullet = require("./PKG/CatchFish/DrillBullet");
const PKG_Generic_Error = require("./PKG/Generic/Error");
const PKG_Generic_Ping = require("./PKG/Generic/Ping");
const PKG_Generic_Pong = require("./PKG/Generic/Pong");
const PKG_CatchFish_Client_EnterSuccess = require("./PKG/CatchFish_Client/EnterSuccess");
const PKG_CatchFish_Client_FrameEvents = require("./PKG/CatchFish_Client/FrameEvents");
const PKG_Client_CatchFish_Enter = require("./PKG/Client_CatchFish/Enter");
const PKG_Client_CatchFish_Bet = require("./PKG/Client_CatchFish/Bet");
const PKG_Client_CatchFish_Fire = require("./PKG/Client_CatchFish/Fire");
const PKG_Client_CatchFish_Hit = require("./PKG/Client_CatchFish/Hit");
const PKG_CatchFish_Scene = require("./PKG/CatchFish/Scene");
const PKG_CatchFish_Player = require("./PKG/CatchFish/Player");
const PKG_CatchFish_FishBorn = require("./PKG/CatchFish/FishBorn");
const PKG_CatchFish_Way = require("./PKG/CatchFish/Way");
const PKG_CatchFish_Configs_FuryCannon = require("./PKG/CatchFish/Configs/FuryCannon");
const PKG_CatchFish_DrillCannon = require("./PKG/CatchFish/DrillCannon");
const PKG_CatchFish_FuryCannon = require("./PKG/CatchFish/FuryCannon");
const PKG_CatchFish_LightWeapon = require("./PKG/CatchFish/LightWeapon");
const PKG_CatchFish_DrillWeapon = require("./PKG/CatchFish/DrillWeapon");
const PKG_CatchFish_FuryWeapon = require("./PKG/CatchFish/FuryWeapon");
const PKG_CatchFish_Events_Enter = require("./PKG/CatchFish/Events/Enter");
const PKG_CatchFish_BombWeapon = require("./PKG/CatchFish/BombWeapon");
const PKG_CatchFish_DrillFish = require("./PKG/CatchFish/DrillFish");
const PKG_CatchFish_FuryFish = require("./PKG/CatchFish/FuryFish");
const PKG_CatchFish_BombFish = require("./PKG/CatchFish/BombFish");
const PKG_CatchFish_BigFish = require("./PKG/CatchFish/BigFish");
const PKG_CatchFish_RoundFish = require("./PKG/CatchFish/RoundFish");
const PKG_CatchFish_WayFish = require("./PKG/CatchFish/WayFish");
const PKG_CatchFish_LightFish = require("./PKG/CatchFish/LightFish");
const PKG_CatchFish_Configs_DrillCannon = require("./PKG/CatchFish/Configs/DrillCannon");

module.exports = function (md: MsgDecoder) {
    md.register(PKG_CatchFish_Item);
    md.register(PKG_CatchFish_MoveItem);
    md.register(PKG_CatchFish_Events_Event);
    md.register(PKG_CatchFish_Fish);
    md.register(PKG_CatchFish_Configs_Item);
    md.register(PKG_CatchFish_Stages_StageElement);
    md.register(PKG_CatchFish_Weapon);
    md.register(PKG_CatchFish_ColorFish);
    md.register(PKG_CatchFish_Configs_Fish);
    md.register(PKG_CatchFish_Bullet);
    md.register(PKG_CatchFish_Configs_Cannon);
    md.register(PKG_CatchFish_Cannon);
    md.register(PKG_CatchFish_Stages_Emitter_RandomFishs);
    md.register(PKG_CatchFish_Stages_Monitor_KeepBigFish);
    md.register(PKG_CatchFish_Events_NoMoney);
    md.register(PKG_CatchFish_Events_Refund);
    md.register(PKG_CatchFish_Events_FishDead);
    md.register(PKG_CatchFish_Events_PushWeapon);
    md.register(PKG_CatchFish_Events_Fire);
    md.register(PKG_CatchFish_Events_CloseAutoFire);
    md.register(PKG_CatchFish_Events_CannonSwitch);
    md.register(PKG_CatchFish_Events_CloseAutoLock);
    md.register(PKG_CatchFish_Events_Aim);
    md.register(PKG_CatchFish_Events_OpenAutoLock);
    md.register(PKG_CatchFish_Events_PushFish);
    md.register(PKG_CatchFish_Events_OpenAutoFire);
    md.register(PKG_Generic_Success);
    md.register(PKG_CatchFish_Events_DebugInfo);
    md.register(PKG_CatchFish_Stages_Stage);
    md.register(PKG_CatchFish_Stages_Monitor_KeepFatFish);
    md.register(PKG_CatchFish_Stages_Monitor_KeepBombFish);
    md.register(PKG_CatchFish_Stages_Emitter_RingFishs);
    md.register(PKG_CatchFish_Stages_Emitter_CircleFishs);
    md.register(PKG_CatchFish_Configs_Config);
    md.register(PKG_CatchFish_Configs_SpriteFrame);
    md.register(PKG_CatchFish_Configs_Physics);
    md.register(PKG_CatchFish_Configs_FishSpriteFrame);
    md.register(PKG_CatchFish_Configs_BigFish);
    md.register(PKG_CatchFish_Configs_ColorFish);
    md.register(PKG_CatchFish_Configs_Weapon);
    md.register(PKG_CatchFish_Events_CannonCoinChange);
    md.register(PKG_CatchFish_Events_Leave);
    md.register(PKG_CatchFish_FuryBullet);
    md.register(PKG_CatchFish_DrillBullet);
    md.register(PKG_Generic_Error);
    md.register(PKG_Generic_Ping);
    md.register(PKG_Generic_Pong);
    md.register(PKG_CatchFish_Client_EnterSuccess);
    md.register(PKG_CatchFish_Client_FrameEvents);
    md.register(PKG_Client_CatchFish_Enter);
    md.register(PKG_Client_CatchFish_Bet);
    md.register(PKG_Client_CatchFish_Fire);
    md.register(PKG_Client_CatchFish_Hit);
    md.register(PKG_CatchFish_Scene);
    md.register(PKG_CatchFish_Player);
    md.register(PKG_CatchFish_FishBorn);
    md.register(PKG_CatchFish_Way);
    md.register(PKG_CatchFish_Configs_FuryCannon);
    md.register(PKG_CatchFish_DrillCannon);
    md.register(PKG_CatchFish_FuryCannon);
    md.register(PKG_CatchFish_LightWeapon);
    md.register(PKG_CatchFish_DrillWeapon);
    md.register(PKG_CatchFish_FuryWeapon);
    md.register(PKG_CatchFish_Events_Enter);
    md.register(PKG_CatchFish_BombWeapon);
    md.register(PKG_CatchFish_DrillFish);
    md.register(PKG_CatchFish_FuryFish);
    md.register(PKG_CatchFish_BombFish);
    md.register(PKG_CatchFish_BigFish);
    md.register(PKG_CatchFish_RoundFish);
    md.register(PKG_CatchFish_WayFish);
    md.register(PKG_CatchFish_LightFish);
    md.register(PKG_CatchFish_Configs_DrillCannon);
};
